name: Python check style
on:
  push:
    branches:
      - news
jobs:
  check-style-python:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone project
        uses: actions/checkout@v2

      - name: Set version python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check style
        run: |
          pip install pycodestyle
          pycodestyle .
    
